


#Con esto se pueden extraer partes de la cadena
#PROGRAMA: APLICAR EL CONCEPTO DE SLICING

texto = "PROGRAMACION"

#LA ESTRUCTURA DEL SLICING ES [INICIO:FIN], EL ULTIMO CARACTER NO CUENTA PORQUE SE CONSIDERA HASTA EL ANTERIOR.

# 1. BASICO [INICIO, FIN]
print(texto[0:4]) #"PROG" (EL INDICE 4 NO SE INCLUYE)


#SI NO SE PONE EL INICIO CUENTA DESDE EL PRIMER CARACTER, OSEA 0
# 2. ATAJO DESDE EL INICIO [:FIN] 
print(texto[:6]) #"PROGRA" (ASUME DESDE EL INCIO 0)


# 3. ATAJO HASTA EL FINAL [INICIO:]
print(texto[8:]) #"CION" (HASTA EL ULTIMO CARACTER)

# 4. INDICES NEGATIVOS
print(texto[-4:]) #"ACION" (CUENTA DESDE EL FINAL HACIA ATRAS, -1 ES LA ULTIMA LETRA)

# 5. INVERTIR CADENA - PASOS [::PASO] 
print(texto[::-5]) #"NOICAMARGORP" (INVIERTE LA CADENA COMPLETA)



